const InitialRecipes = [
    { id: 'hoff_v60', name: "James Hoffmann (Ultimate)", method: "V60", ratio: 16.6, temp: 98, clicks: 85, total: 210, steps: [{ time: 0, targetPct: 0.15, title: "Bloom", tip: "Gire o dripper (Swirl).", pourTime: 10 }, { time: 45, targetPct: 0.60, title: "1º Despejo", tip: "60% da água até 1:15.", pourTime: 30 }, { time: 75, targetPct: 1.00, title: "2º Despejo", tip: "Até o peso total.", pourTime: 30 }] },
    { id: 'kasuya_std', name: "Tetsu Kasuya (4:6 Std)", method: "V60", ratio: 15, temp: 92, clicks: 125, total: 210, steps: [{ time: 0, targetPct: 0.20, title: "1º Despejo", tip: "Acidez. Moagem Coarse.", pourTime: 10 }, { time: 45, targetPct: 0.40, title: "2º Despejo", tip: "Doçura. Espere drenar.", pourTime: 10 }, { time: 90, targetPct: 1.00, title: "Finalização", tip: "Drenagem total.", pourTime: 30 }] },
    { id: 'kasuya_sweet', name: "Tetsu Kasuya (Doçura)", method: "V60", ratio: 15, temp: 90, clicks: 125, total: 210, steps: [{ time: 0, targetPct: 0.16, title: "1º Despejo", tip: "Menos água destaca o doce.", pourTime: 10 }, { time: 45, targetPct: 0.40, title: "2º Despejo", tip: "Compense o volume.", pourTime: 15 }, { time: 90, targetPct: 1.00, title: "Finalização", tip: "Drenagem.", pourTime: 30 }] },
    { id: 'april_std', name: "April Method", method: "V60", ratio: 15, temp: 92, clicks: 100, total: 150, steps: [{ time: 0, targetPct: 0.50, title: "1º Despejo", tip: "100g rápidos.", pourTime: 12 }, { time: 35, targetPct: 1.00, title: "2º Despejo", tip: "100g centro.", pourTime: 12 }] },
    { id: 'hedrick_sweet', name: "Lance Hedrick", method: "V60", ratio: 15, temp: 95, clicks: 90, total: 195, steps: [{ time: 0, targetPct: 0.20, title: "Bloom Agressivo", tip: "Agite bem o pó.", pourTime: 10 }, { time: 60, targetPct: 1.00, title: "Despejo Único", tip: "Fluxo suave.", pourTime: 40 }] },
    { id: 'esp_classic', name: "Espresso Clássico", method: "Espresso", ratio: 2, temp: 94, clicks: 40, total: 30, steps: [{ time: 0, targetPct: 1.00, title: "Extração", tip: "Alvo: 36-40g.", pourTime: 30 }] },
    { id: 'fp_classic', name: "Prensa Clássica", method: "Prensa Francesa", ratio: 15, temp: 93, clicks: 150, total: 240, steps: [{ time: 0, targetPct: 1.00, title: "Infusão", tip: "Aguarde até 3:30.", pourTime: 10 }] }
];
